/*
 * HKEYPAD_private.h
 *
 *  Created on: Jul 30, 2023
 *      Author: OMAR YAHYA
 */

#ifndef HKEYPAD_HKEYPAD_PRIVATE_H_
#define HKEYPAD_HKEYPAD_PRIVATE_H_

#define HKEYPAD_ROW_SIZE        4
#define HKEYPAD_COLUMN_SIZE     4

#define HKEYPAD_NO_PRESSED_KEY 0xFF
#define HKEYPAD_KEY_PRESSED     0

#define HKEYPAD_ROWS    {HKEYPAD_R1,HKEYPAD_R2,HKEYPAD_R3,HKEYPAD_R4}
#define HKEYPAD_COLUMNS {HKEYPAD_C1,HKEYPAD_C2,HKEYPAD_C3,HKEYPAD_C4}

#endif /* HKEYPAD_HKEYPAD_PRIVATE_H_ */
